### ISSUE TITLE
`miden-stdlib` docs failing to build for docs.rs

### ISSUE THREAD

**Issue by igamigo** [0xPolygonMiden/miden-vm#1282] opened 2024-03-15 19:44 UTC
Looks like the custom build script for `miden-stdlib` is failing to run on the docs.rs pipeline due with an error stating that the filesystem is read-only: https://docs.rs/crate/miden-stdlib/0.8.0/builds/1140597
As a consequence, the client docs are also failing to build as well: https://docs.rs/crate/miden-client/0.1.0/builds/1159375

**Comment by hackaugusto** [comment] 2024-04-30 23:30
related: https://github.com/0xPolygonMiden/miden-vm/issues/1208

**Comment by bobbinth** [comment] 2024-05-03 22:54
Ah - seems like this is an exact duplicate of #1208. So, I'll close this one in favor of that one.

**Closed by bobbinth** 2024-05-03 22:54 UTC
