### ISSUE TITLE
Finish tiered Sparse Merkle Tree

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/miden-vm#1028] opened 2023-07-28 15:50 UTC
Maybe a copy, but I couldn't find an issue about that

**Comment by bobbinth** [comment] 2023-08-30 07:01
Duplicate of #258 which was closed by https://github.com/0xPolygonMiden/miden-vm/pull/1046, https://github.com/0xPolygonMiden/miden-vm/issues/1048, https://github.com/0xPolygonMiden/miden-vm/pull/1036 and other related PRs.

**Closed by bobbinth** 2023-08-30 07:01 UTC
